version: "3"
services:
  mq:
    container_name: sendmail-mq
    restart: always
    image: rabbitmq:3.7-alpine
    ports:
    - 5672:5672
    - 15672:15672
  waitmq:
    container_name: sendmail-waitmq
    restart: on-failure
    image: vbogretsov/waitamqp:0.1.0
    environment:
    - WAITAMQP_URL=amqp://guest:guest@mq